export const CONFIG = {
  canvas: { width: 960, height: 600 },

  board: {
    cols: 7,
    rows: 6,
    cellSize: 64,
    offsetY: 120,
    border: 8,
  },

  game: {
    initialHealth: 100,
    healthDecayBase: 2,
    healthDecayPerLevel: 0.5,
    healthPerMatch: 8,
    scoreNormal: 100,
    scoreLine: 300,
    scoreArea: 500,
    scorePerLevel: 3000,
    maxCombo: 10,
    deadeyeMax: 100,
    deadeyePerMatch: 8,
    deadeyePerLine: 15,
    deadeyePerArea: 25,

    regularTypeCount: 5,
    lassoMax: 3,
    cowsToCapture: 3,
  },

  puzzle: {
    shiftSpeed: 4,
    slideDuration: 0.5,
    resolveDuration: 1.0,
    exitDuration: 0.4,
  },

  shootout: {
    hostilesPerWave: 3,
    friendliesPerWave: 1,
    introDuration: 1.0,
    telegraphDuration: 0.4,
    riseDuration: 0.25,
    visibleDuration: 1.5,
    fallDuration: 0.25,
    silhouetteStagger: 0.5,
    betweenWaveDuration: 0.5,
    completeDuration: 1.5,
    gripPerHostile: 3,
    gripPerFriendly: 2,
  },

  animation: {
    swapSpeed: 12,
    removeSpeed: 8,
    gravitySpeed: 15,
    pieceFloatAmp: 2,
    pulseSpeed: 4,
    checkDelay: 0.1,
  },

  colors: {
    boardBorder: '#5c3a21',
    boardBg: '#8b5a2b',
    boardInner: '#a0724a',
    cellLight: '#c49a6c',
    cellDark: '#b8895e',
    hudGold: '#ffd700',
    hudOrange: '#ff8c00',
    hudWhite: '#ffffff',
    hudGray: '#aaaaaa',
    healthBarBg: '#5c3a21',
    gameOverRed: '#ff3333',
    menuBg: 'rgba(0,0,0,0.5)',
    gameOverBg: 'rgba(0,0,0,0.7)',
    gunBody: '#2a1a0a',
    gunGrip: '#1a0f05',
    gunFrame: '#3e2723',
    gunBarrel: '#5d4037',
    skyGradStart: '#1a0533',
    skyGradMid: '#4a1942',
    skyGradWarm: '#c84b31',
    skyGradPink: '#fec89a',
    skyGradGold: '#ffd700',
    groundDark: '#2d1b0e',
    groundBrown: '#3e2723',
    groundDeep: '#1a0f0a',
    groundBlack: '#0d0705',
    shrubBrown: '#2d1f14',
    shrubDark: '#1a0f0a',
  },

  effects: {
    particleCountNormal: 20,
    particleCountLine: 60,
    particleCountArea: 120,
    particleLifeNormal: 0.6,
    particleLifeLine: 0.9,
    particleLifeArea: 1.0,
    floatingTextDuration: {
      bang: 0.5,
      line: 1.0,
      area: 1.2,
    },
  },

  boss: {
    introDuration: 1.5,
    telegraphDuration: 0.7,
    windowDuration: 1.2,
    hitDuration: 0.3,
    missDuration: 0.5,
    victoryDuration: 2.0,
    health: 10,
  },

  pieceTypes: [
    { name: 'Outlaw', color: '#ff3333' },
    { name: 'Bandit', color: '#1a1a1a' },
    { name: 'Snake', color: '#33cc33' },
    { name: 'Coyote', color: '#cccccc' },
    { name: 'Vulture', color: '#cc6600' },
    { name: 'Cow', color: '#8b6914' },
    { name: 'Heart', color: '#ff0044' },
    { name: 'Lasso', color: '#c49a6c' },
  ] as { name: string; color: string }[],
} as const;
